# Generated by Django 3.0.8 on 2020-07-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registertopics', '0003_auto_20200718_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='author_name',
            field=models.CharField(default='Pawan Kumar Mishra', max_length=60),
        ),
    ]
