# Generated by Django 3.0.8 on 2020-07-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registertopics', '0004_auto_20200718_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_subject',
            field=models.CharField(choices=[('QuantumElectronics', 'Quantum Electronics'), ('VLSICircuitDesignandDeviceModeling', 'VLSI Circuit Design and Device Modeling'), ('ModernCommunicationSystems', 'Modern Communication Systems'), ('MicrowaveElectronics', 'Microwave Electronics')], max_length=50),
        ),
    ]
