# Generated by Django 3.0.8 on 2020-07-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registertopics', '0007_auto_20200719_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=models.CharField(max_length=200),
        ),
    ]
